import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync, statSync } from 'node:fs'
import { join } from 'node:path'
import * as THREE from 'three'
import { partFromYaml } from '../src/shared/part-yaml'

/**
 * The robot-kit part meshes: three generated by `scripts/robot-kit-meshes.mjs`
 * (Pico 2 W, MX1508, 4×AA pack) and the HC-SR04 shipped from the FreeCAD
 * library. Each part's `parts.yml` must name the model it ships, authored in
 * millimetres, and a generated model must match the part's 2-D footprint and
 * sit board-flat, Z up, underside on z = 0 — the convention every library mesh
 * follows so a placed part rests on the floor rather than in it.
 */
const LIB = join(__dirname, '..', 'examples', 'parts', 'snakie-standard')

// The generator is plain ESM JS with no type declarations; import it untyped.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const gen = (await import('../scripts/robot-kit-meshes.mjs')) as any
const PARTS = gen.PARTS as Record<string, { footprint: [number, number] }>

function partOf(id: string) {
  return partFromYaml(readFileSync(join(LIB, id, 'parts.yml'), 'utf8'))
}

function bounds(id: string): THREE.Box3 {
  return new THREE.Box3().setFromObject(gen.partGroup(id) as THREE.Group)
}

describe('robot-kit meshes (generated)', () => {
  it('covers the Pico 2 W, the MX1508 and the 4×AA pack', () => {
    expect(Object.keys(PARTS).sort()).toEqual(['battery-aa-4', 'mx1508', 'pico2w'])
  })

  for (const id of Object.keys(PARTS)) {
    describe(id, () => {
      const part = partOf(id)
      const box = bounds(id)

      it('ships the generated model, authored in millimetres, with no fix-up', () => {
        expect(part.mesh).toBe(gen.MESH_FILENAME)
        expect(part.meshUnits).toBe('mm')
        expect(part.meshRotation).toBeUndefined()
        expect(part.meshOffset).toBeUndefined()
        const file = join(LIB, id, gen.MESH_FILENAME)
        expect(existsSync(file), file).toBe(true)
        // Binary STL: 84-byte header + 50 bytes per triangle, and not huge.
        const size = statSync(file).size
        expect((size - 84) % 50).toBe(0)
        expect(size).toBeLessThan(400 * 1024)
      })

      it("matches the part's 2-D footprint and stands on z = 0", () => {
        const [w, h] = PARTS[id].footprint
        expect(part.dimensions).toEqual({ width: w, height: h })
        // Centred in x/y; y may overhang slightly for connectors and leads.
        expect(box.min.x).toBeCloseTo(-w / 2, 1)
        expect(box.max.x).toBeCloseTo(w / 2, 1)
        expect(box.min.y).toBeCloseTo(-h / 2, 1)
        expect(box.max.y).toBeGreaterThanOrEqual(h / 2 - 0.01)
        expect(box.max.y).toBeLessThan(h / 2 + 10)
        expect(box.min.z).toBeCloseTo(0, 3)
        expect(box.max.z).toBeGreaterThan(1)
      })
    })
  }

  it('the Pico is a 1 mm board with 40 castellations and 4 holes, 3.6 mm tall overall', () => {
    const box = bounds('pico2w')
    expect(box.max.z).toBeCloseTo(3.6, 1)
    const shape = gen.picoShape() as THREE.Shape
    expect(shape.holes).toHaveLength(4)
    const pico = gen.PICO as { pads: { count: number; pitchMm: number } }
    expect(pico.pads.count * 2).toBe(40)
    expect(pico.pads.pitchMm).toBe(2.54)
  })

  it('the 4×AA pack stacks two cells high', () => {
    const pack = gen.AA_PACK as { wallMm: number; layers: number; cell: { diameterMm: number } }
    expect(pack.layers).toBe(2)
    expect(gen.aaPackHeightMm()).toBeCloseTo(pack.wallMm + 2 * pack.cell.diameterMm)
    expect(bounds('battery-aa-4').max.z).toBeCloseTo(gen.aaPackHeightMm(), 3)
  })
})

describe('hc-sr04 mesh (FreeCAD-library)', () => {
  const part = partOf('hc-sr04')

  it('ships the library STL in millimetres, offset so its pins rest on z = 0', () => {
    expect(part.mesh).toBe('model.stl')
    expect(part.meshUnits).toBe('mm')
    expect(part.meshRotation).toBeUndefined()
    expect(part.meshOffset).toEqual([0, 2.5, 3.5])
    const file = join(LIB, 'hc-sr04', 'model.stl')
    expect(existsSync(file)).toBe(true)
    expect((statSync(file).size - 84) % 50).toBe(0)
  })

  it('credits the source in its help article', () => {
    const help = readFileSync(join(LIB, 'hc-sr04', 'help.md'), 'utf8')
    expect(help).toMatch(/FreeCAD-library/)
    expect(help).toMatch(/CC-BY 3\.0/)
  })
})
